export const data = [
  {
    id: '1',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '2',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '3',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '4',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '5',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '6',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '7',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '8',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '9',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '10',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '11',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '12',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '13',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '14',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '15',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '16',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '17',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '18',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '19',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
  {
    id: '20',
    title: 'lorem Lorem ipsum dolor Lorem ipsum dolor',
    text: 'Lorem Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor ipsum dolor sit amet consectetur adipisicing elit. Dolorem estvel',
    avatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    dateString: '2021-09-20T18:21:32.854Z',
  },
];
